TVSeries4U/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/home', to: 'static_pages#home'
  get '/contact', to: 'static_pages#contact'

  ##sesiones
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/signup', to: 'users#new'

  # Series, capitulos y reviews
  resources :series do
    resources :seasons do
      resources :chapters do
        resources :chapters_reviews

        resources :seens, only: [:create, :destroy]
      end
      
      resources :seasons_reviews
    end

    resources :series_news
    resources :sreviews
  end
  resources :perfilseries,        only: [:create, :destroy]

  # Users
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]

  # Families
  resources :families do
    resources :family_invites
    resources :family_members
  end
  
  # Series fill
  resources :genres
  resources :genres_relationships,       only: [:create, :destroy]

  resources :actors do
    resources :actors_news
  end
  resources :actors_relationships,       only: [:create, :destroy]

  resources :directors do
    resources :directors_news
  end
  resources :directors_relationships,       only: [:create, :destroy]

  resources :news_feed,           only: [:index]
end

TVSeries4U/app/models/director.rb
class Director < ApplicationRecord
  # Series
  has_many :series_directors, dependent: :destroy
  has_many :series, through: :series_directors, source: :serie

  # Followers
  has_many :directors_relationship, dependent: :destroy
  has_many :followers, through: :directors_relationship, source: :user  
  
  # News
  has_many :news, foreign_key: "director_id", class_name: "DirectorsNew", dependent: :destroy
  has_many :user_news, through: :news, source: :user

  # Validates
  validates :name, presence: true
  validates :last_name, presence: true
  validates_uniqueness_of :name, :scope => [:last_name], case_sensitive: false
  validates_uniqueness_of :last_name, :scope => [:name], case_sensitive: false
  
  def full_name
    "#{name} #{last_name}"
  end

  def self.search(search)
    where("name LIKE ? OR last_name LIKE ?", "%#{search}%", "%#{search}%") 
  end
end

TVSeries4U/app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :find_director, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: [:create, :edit, :update, :destroy, :new]

  def new
    @director = Director.new
  end

  def edit
  end

  def update
    if @director.update(director_params)
      redirect_to @director
    else
      render 'edit'
    end
  end

  def create
    @director = Director.new(director_params)

    if @director.save
      flash[:success] = "Director Created"
      redirect_to @director
    else
      render 'new'
    end
  end

  def index
	@directors = Director.all.order("directors.name ASC").paginate(page: params[:page])
  end

  def show
    @director = Director.find(params[:id])
    @series = @director.series
  end

  def destroy
    @director.destroy
    flash[:danger] = "Director Deleted"
    redirect_to directors_path
  end

  private
    def find_director
      @director = Director.find(params[:id])
    end

    def director_params
      params.require(:director).permit(:name, :last_name)
    end
    
    def admin_user
      flash[:danger] = "Restringed action, only admins" unless current_user.admin?
      redirect_to(root_url) unless current_user.admin?
    end
end

TVSeries4U/app/helpers/directors_helper.rb
module DirectorsHelper
end

TVSeries4U/app/views/directors/_follow_button.html.erb
<div class="row">
	<div class="col-xs-12" id="follow_form">
	  <% if current_user.following_director?(@director) %>
	    <%= form_for(current_user.directors_relationship.find_by(director_id: @director.id), html: { method: :delete }) do |f| %> 
	      <%= hidden_field_tag :director_id, @director.id %>
	      <%= f.submit "Unfollow", class: "btn" %>
	    <% end %>
	  <% else %>
	    <%= form_for(current_user.directors_relationship.build) do |f| %>
	      <%= hidden_field_tag :director_id, @director.id %>
	      <%= f.submit "Follow", class: "btn btn-primary" %>
	    <% end %>
	  <% end %>
	</div>
</div>

TVSeries4U/app/views/directors/_form.html.erb
<%= form_for @director do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name, class: 'form-control' %>
  
  <%= f.submit yield(:submit_text), class: "btn btn-primary" %>
<% end %>

TVSeries4U/app/views/directors/_index.html.erb
<%= will_paginate @directors %>

<% if @directors.empty? %>
  <h5 class="text-center">No directors to show.</h3>
<% end %>

<ul class="directors">
  <% @directors.each do |director| %>
    <li class="h-title">
      <%= link_to director.full_name, director %>
      <% if logged_in && current_user.admin? %>
        <%= link_to "Delete Director", director, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-xs btn-danger"%>
      <% end %>
    </li>
  <% end %>
</ul>

<%= will_paginate @directors %>

TVSeries4U/app/views/directors/edit.html.erb
<% provide(:title, "Edit director") %>
<h1>Update actor</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% provide(:submit_text, "Save changes") %>
    <%= render "form" %>
  </div>
</div>

TVSeries4U/app/views/directors/index.html.erb
<% provide(:title, "All directors") %>

<% if logged_in && current_user.admin %>
  <div>
    <%= link_to "Add Director", new_director_path, class: "btn btn-success" %>
  </div>
<% end %>

<h1>All directors</h1>
<%= render "index" %>

TVSeries4U/app/views/directors/new.html.erb
<% provide(:title, 'Create director') %>
<h1>New Director</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% provide(:submit_text, "Create Director") %>
    <%= render "form" %>
  </div>
</div>

TVSeries4U/app/views/directors/show.html.erb
<% provide(:title, "Director #{@director.full_name}") %>

<div class="row">
  <div class="col-md-4">
    <div class="user_info">
      <div>
        <h4 class="h-title text-center">
          <div></div>
		  <ls>
		    <%= @director.full_name %>
		  </ls>
		  <div></div>
        </h4>
      </div>
      <hr>
  	  <%= render "directors/follow_button" if logged_in %>
      <% if logged_in && current_user.admin %>
        <br>
        <%= link_to "Edit Director", edit_director_path(@director), class: "btn btn-default col-xs-12"%>
        <br><br><br>
        <%= link_to "Delete Director", @director, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger col-xs-12"%>
      <%end%>
    </div>
  </div>
  <div class="col-md-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="active"><a data-toggle="tab" href="#series">Series (<%= @director.series.count %>)</a></li>
      <li><a data-toggle="tab" href="#news">News (<%= @director.news.count %>)</a></li>
    </ul>

    <div class="tab-content">
      <div id="series" class="tab-pane fade in active">
  	    <%= render "series/serie", :@series => @director.series %>
      </div>
      <div id="news" class="tab-pane fade">
  	    <% provide(:name, "director") %>
	    <%= render "shared/news", :@class => @director %>
      </div>
    </div>
  </div>
</div>